$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
build:
  path: .
inference_config:
  liveness_route:
    path: /health
    port: 8080
  readiness_route:
    path: /health
    port: 8080
  scoring_route:
    path: /score
    port: 8080
